# Downloading Market and Fundamental Data with `yfinance`

## Imports & Settings

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
import pandas as pd
import yfinance as yf

## How to work with a Ticker object

In [6]:
symbol = 'META'
ticker = yf.Ticker(symbol)

### Show ticker info

In [7]:
pd.Series(ticker.info).head(20)

address1                                                        1 Meta Way
city                                                            Menlo Park
state                                                                   CA
zip                                                                  94025
country                                                      United States
phone                                                         650 543 4800
website                                        https://investor.atmeta.com
industry                                    Internet Content & Information
industryKey                                   internet-content-information
industryDisp                                Internet Content & Information
sector                                              Communication Services
sectorKey                                           communication-services
sectorDisp                                          Communication Services
longBusinessSummary      Meta Platforms, Inc. engages in the developmen...
fullTimeEmployees                                                    74067
companyOfficers          [{'maxAge': 1, 'name': 'Mr. Mark Elliot Zucker...
auditRisk                                                               10
boardRisk                                                               10
compensationRisk                                                        10
shareHolderRightsRisk                                                   10
dtype: object

### Get market data

In [8]:
data = ticker.history(period='5d',
                      interval='1m',
                      start=None,
                      end=None,
                      actions=True,
                      auto_adjust=True,
                      back_adjust=False)
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1950 entries, 2025-03-10 09:30:00-04:00 to 2025-03-14 15:59:00-04:00
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Open          1950 non-null   float64
 1   High          1950 non-null   float64
 2   Low           1950 non-null   float64
 3   Close         1950 non-null   float64
 4   Volume        1950 non-null   int64
 5   Dividends     1950 non-null   float64
 6   Stock Splits  1950 non-null   float64
dtypes: float64(6), int64(1)
memory usage: 121.9 KB

### View company actions

In [9]:
# show actions (dividends, splits)
ticker.actions

                           Dividends  Stock Splits
Datetime
2025-03-14 09:30:00-04:00      0.525           0.0

In [10]:
ticker.dividends

Datetime
2025-03-14 09:30:00-04:00    0.525
Name: Dividends, dtype: float64

In [11]:
ticker.splits

Series([], Name: Stock Splits, dtype: float64)

### Annual and Quarterly Financial Statement Summary

In [12]:
ticker.financials

,2024-12-31,2023-12-31,2022-12-31,2021-12-31,2020-12-31
Tax Effect Of Unusual Items,-81420000.0,-64416000.0,-15795000.0,-23380000.0,NaN
Tax Rate For Calcs,0.118,0.176,0.195,0.167,NaN
Normalized EBITDA,87566000000.0,59418000000.0,37771000000.0,55414000000.0,NaN
Total Unusual Items,-690000000.0,-366000000.0,-81000000.0,-140000000.0,NaN
Total Unusual Items Excluding Goodwill,-690000000.0,-366000000.0,-81000000.0,-140000000.0,NaN
Net Income From Continuing Operation Net Minority Interest,62360000000.0,39098000000.0,23200000000.0,39370000000.0,NaN
Reconciled Depreciation,15498000000.0,11178000000.0,8686000000.0,7967000000.0,NaN
Reconciled Cost Of Revenue,30161000000.0,25959000000.0,25249000000.0,22649000000.0,NaN
EBITDA,86876000000.0,59052000000.0,37690000000.0,55274000000.0,NaN
EBIT,71378000000.0,47874000000.0,29004000000.0,47307000000.0,NaN
Net Interest Income,1973000000.0,1043000000.0,-44000000.0,671000000.0,NaN
Interest Expense,715000000.0,446000000.0,185000000.0,23000000.0,NaN
Interest Income,2517000000.0,1639000000.0,461000000.0,484000000.0,NaN
Normalized Income,62968580000.0,39399584000.0,23265205000.0,39486620000.0,NaN
Net Income From Continuing And Discontinued Operation,62360000000.0,39098000000.0,23200000000.0,39370000000.0,NaN
Total Expenses,95121000000.0,88151000000.0,87665000000.0,71176000000.0,NaN
Total Operating Income As Reported,69380000000.0,46751000000.0,28944000000.0,46753000000.0,NaN
Diluted Average Shares,2614000000.0,2629000000.0,2702000000.0,2859000000.0,NaN
Basic Average Shares,2534000000.0,2574000000.0,2687000000.0,2815000000.0,NaN
Diluted EPS,23.86,14.87,8.59,13.77,NaN
Basic EPS,24.61,15.19,8.63,13.99,NaN
Diluted NI Availto Com Stockholders,62360000000.0,39098000000.0,23200000000.0,39370000000.0,NaN
Net Income Common Stockholders,62360000000.0,39098000000.0,23200000000.0,39370000000.0,NaN
Otherunder Preferred Stock Dividend,NaN,NaN,NaN,NaN,0.0
Net Income,62360000000.0,39098000000.0,23200000000.0,39370000000.0,NaN
Net Income Including Noncontrolling Interests,62360000000.0,39098000000.0,23200000000.0,39370000000.0,NaN
Net Income Continuous Operations,62360000000.0,39098000000.0,23200000000.0,39370000000.0,NaN
Tax Provision,8303000000.0,8330000000.0,5619000000.0,7914000000.0,NaN
Pretax Income,70663000000.0,47428000000.0,28819000000.0,47284000000.0,NaN
Other Income Expense,-690000000.0,-366000000.0,-81000000.0,-140000000.0,NaN
Other Non Operating Income Expenses,NaN,NaN,-320000000.0,210000000.0,-34000000.0
Special Income Charges,NaN,NaN,NaN,0.0,0.0
Gain On Sale Of Security,-690000000.0,-366000000.0,-81000000.0,-140000000.0,NaN
Net Non Operating Interest Income Expense,1973000000.0,1043000000.0,-44000000.0,671000000.0,NaN
Total Other Finance Cost,-171000000.0,150000000.0,320000000.0,-210000000.0,NaN
Interest Expense Non Operating,715000000.0,446000000.0,185000000.0,23000000.0,NaN
Interest Income Non Operating,2517000000.0,1639000000.0,461000000.0,484000000.0,NaN
Operating Income,69380000000.0,46751000000.0,28944000000.0,46753000000.0,NaN
Operating Expense,64960000000.0,62192000000.0,62416000000.0,48527000000.0,NaN
Research And Development,43873000000.0,38483000000.0,35338000000.0,24655000000.0,NaN
Selling General And Administration,21087000000.0,23709000000.0,27078000000.0,23872000000.0,NaN
Selling And Marketing Expense,11347000000.0,12301000000.0,15262000000.0,14043000000.0,NaN
General And Administrative Expense,9740000000.0,11408000000.0,11816000000.0,9829000000.0,NaN
Other Gand A,9740000000.0,11408000000.0,11816000000.0,9829000000.0,NaN
Gross Profit,134340000000.0,108943000000.0,91360000000.0,95280000000.0,NaN
Cost Of Revenue,30161000000.0,25959000000.0,25249000000.0,22649000000.0,NaN
Total Revenue,164501000000.0,134902000000.0,116609000000.0,117929000000.0,NaN
Operating Revenue,162779000000.0,133844000000.0,115801000000.0,117208000000.0,NaN

In [13]:
ticker.quarterly_financials

,2024-12-31,2024-09-30,2024-06-30,2024-03-31,2023-12-31,2023-09-30
Tax Effect Of Unusual Items,-44365234.375,1320000.0,-18480000.0,-32560000.0,-10126137.918724,NaN
Tax Rate For Calcs,0.115234,0.12,0.11,0.22,0.166002,NaN
Normalized EBITDA,28648000000.0,22046000000.0,19039000000.0,17832000000.0,20176000000.0,NaN
Total Unusual Items,-385000000.0,11000000.0,-168000000.0,-148000000.0,-61000000.0,NaN
Total Unusual Items Excluding Goodwill,-385000000.0,11000000.0,-168000000.0,-148000000.0,-61000000.0,NaN
Net Income From Continuing Operation Net Minority Interest,20838000000.0,15688000000.0,13465000000.0,12369000000.0,14017000000.0,NaN
Reconciled Depreciation,4460000000.0,4027000000.0,3637000000.0,3374000000.0,3172000000.0,NaN
Reconciled Cost Of Revenue,8839000000.0,7375000000.0,7308000000.0,6640000000.0,7695000000.0,NaN
EBITDA,28263000000.0,22057000000.0,18871000000.0,17684000000.0,20115000000.0,NaN
EBIT,23803000000.0,18030000000.0,15234000000.0,14310000000.0,16943000000.0,NaN
Net Interest Income,573000000.0,461000000.0,427000000.0,513000000.0,484000000.0,NaN
Interest Expense,251000000.0,208000000.0,128000000.0,127000000.0,136000000.0,NaN
Interest Income,731000000.0,661000000.0,540000000.0,585000000.0,588000000.0,NaN
Normalized Income,21178634765.625,15678320000.0,13614520000.0,12484440000.0,14067873862.081276,NaN
Net Income From Continuing And Discontinued Operation,20838000000.0,15688000000.0,13465000000.0,12369000000.0,14017000000.0,NaN
Total Expenses,25021000000.0,23239000000.0,24224000000.0,22637000000.0,23727000000.0,NaN
Total Operating Income As Reported,23364000000.0,17350000000.0,14847000000.0,13818000000.0,16384000000.0,NaN
Diluted Average Shares,NaN,2600000000.0,2610000000.0,2625000000.0,2630000000.0,2641000000.0
Basic Average Shares,NaN,2529000000.0,2534000000.0,2545000000.0,2566000000.0,2576000000.0
Diluted EPS,NaN,6.03,5.16,4.71,5.33,4.39
Basic EPS,NaN,6.2,5.31,4.86,5.46,4.5
Diluted NI Availto Com Stockholders,20838000000.0,15688000000.0,13465000000.0,12369000000.0,14017000000.0,NaN
Net Income Common Stockholders,20838000000.0,15688000000.0,13465000000.0,12369000000.0,14017000000.0,NaN
Net Income,20838000000.0,15688000000.0,13465000000.0,12369000000.0,14017000000.0,NaN
Net Income Including Noncontrolling Interests,20838000000.0,15688000000.0,13465000000.0,12369000000.0,14017000000.0,NaN
Net Income Continuous Operations,20838000000.0,15688000000.0,13465000000.0,12369000000.0,14017000000.0,NaN
Tax Provision,2714000000.0,2134000000.0,1641000000.0,1814000000.0,2790000000.0,NaN
Pretax Income,23552000000.0,17822000000.0,15106000000.0,14183000000.0,16807000000.0,NaN
Other Income Expense,-385000000.0,11000000.0,-168000000.0,-148000000.0,-61000000.0,NaN
Gain On Sale Of Security,-385000000.0,11000000.0,-168000000.0,-148000000.0,-61000000.0,NaN
Net Non Operating Interest Income Expense,573000000.0,461000000.0,427000000.0,513000000.0,484000000.0,NaN
Total Other Finance Cost,-93000000.0,-8000000.0,-15000000.0,-55000000.0,-32000000.0,NaN
Interest Expense Non Operating,251000000.0,208000000.0,128000000.0,127000000.0,136000000.0,NaN
Interest Income Non Operating,731000000.0,661000000.0,540000000.0,585000000.0,588000000.0,NaN
Operating Income,23364000000.0,17350000000.0,14847000000.0,13818000000.0,16384000000.0,NaN
Operating Expense,16182000000.0,15864000000.0,16916000000.0,15997000000.0,16032000000.0,NaN
Research And Development,12180000000.0,11177000000.0,10537000000.0,9978000000.0,10517000000.0,NaN
Selling General And Administration,4002000000.0,4687000000.0,6379000000.0,6019000000.0,5515000000.0,NaN
Selling And Marketing Expense,3240000000.0,2822000000.0,2721000000.0,2564000000.0,3226000000.0,NaN
General And Administrative Expense,762000000.0,1865000000.0,3658000000.0,3455000000.0,2289000000.0,NaN
Other Gand A,762000000.0,1865000000.0,3658000000.0,3455000000.0,2289000000.0,NaN
Gross Profit,39546000000.0,33214000000.0,31763000000.0,29815000000.0,32416000000.0,NaN
Cost Of Revenue,8839000000.0,7375000000.0,7308000000.0,6640000000.0,7695000000.0,NaN
Total Revenue,48385000000.0,40589000000.0,39071000000.0,36455000000.0,40111000000.0,NaN
Operating Revenue,47866000000.0,40155000000.0,38682000000.0,36075000000.0,39777000000.0,NaN

### Annual and Quarterly Balance Sheet

In [14]:
ticker.balance_sheet

,2024-12-31,2023-12-31,2022-12-31,2021-12-31,2020-12-31
Treasury Shares Number,NaN,0.0,NaN,NaN,NaN
Ordinary Shares Number,2534487662.0,2561000000.0,2614000000.0,2741000000.0,NaN
Share Issued,2534487662.0,2561000000.0,2614000000.0,2741000000.0,NaN
Total Debt,49060000000.0,37234000000.0,26591000000.0,13873000000.0,NaN
Tangible Book Value,161068000000.0,131726000000.0,104510000000.0,105048000000.0,NaN
...,...,...,...,...,...
Cash Cash Equivalents And Short Term Investments,77815000000.0,65403000000.0,40738000000.0,47998000000.0,NaN
Other Short Term Investments,33926000000.0,23541000000.0,26057000000.0,31397000000.0,NaN
Cash And Cash Equivalents,43889000000.0,41862000000.0,14681000000.0,16601000000.0,NaN
Cash Equivalents,36671000000.0,35597000000.0,8505000000.0,9293000000.0,NaN
Cash Financial,7218000000.0,6265000000.0,6176000000.0,7308000000.0,NaN

In [15]:
ticker.quarterly_balance_sheet

,2024-12-31,2024-09-30,2024-06-30,2024-03-31,2023-12-31,2023-09-30,2023-06-30
Treasury Shares Number,NaN,NaN,NaN,NaN,0.0,NaN,NaN
Ordinary Shares Number,2534487662.0,2524000000.0,2533087958.0,2537000000.0,2561000000.0,NaN,NaN
Share Issued,2534487662.0,2524000000.0,2533087958.0,2537000000.0,2561000000.0,NaN,NaN
Total Debt,49060000000.0,49047000000.0,37991000000.0,37633000000.0,37234000000.0,NaN,NaN
Tangible Book Value,161068000000.0,143875000000.0,136109000000.0,128875000000.0,131726000000.0,NaN,NaN
...,...,...,...,...,...,...,...
Cash Cash Equivalents And Short Term Investments,77815000000.0,70900000000.0,58080000000.0,58120000000.0,65403000000.0,NaN,NaN
Other Short Term Investments,33926000000.0,27048000000.0,26035000000.0,25813000000.0,23541000000.0,NaN,NaN
Cash And Cash Equivalents,43889000000.0,43852000000.0,32045000000.0,32307000000.0,41862000000.0,NaN,NaN
Cash Equivalents,36671000000.0,37323000000.0,25886000000.0,25812000000.0,35597000000.0,NaN,NaN
Cash Financial,7218000000.0,6529000000.0,6159000000.0,6495000000.0,6265000000.0,NaN,NaN

### Annual and Quarterly Cashflow Statement

In [16]:
ticker.cashflow

,2024-12-31,2023-12-31,2022-12-31,2021-12-31,2020-12-31
Free Cash Flow,54072000000.0,44068000000.0,19289000000.0,38993000000.0,NaN
Repurchase Of Capital Stock,-30125000000.0,-19774000000.0,-27956000000.0,-44537000000.0,NaN
Repayment Of Debt,-1969000000.0,-1058000000.0,-850000000.0,-677000000.0,NaN
Issuance Of Debt,10432000000.0,8455000000.0,9921000000.0,0.0,NaN
Capital Expenditure,-37256000000.0,-27045000000.0,-31186000000.0,-18690000000.0,NaN
Interest Paid Supplemental Data,486000000.0,448000000.0,0.0,0.0,NaN
Income Tax Paid Supplemental Data,10554000000.0,6607000000.0,6407000000.0,8525000000.0,NaN
End Cash Position,45438000000.0,42827000000.0,15596000000.0,16865000000.0,NaN
Beginning Cash Position,42827000000.0,15596000000.0,16865000000.0,17954000000.0,NaN
Effect Of Exchange Rate Changes,-786000000.0,113000000.0,-638000000.0,-474000000.0,NaN
Changes In Cash,3397000000.0,27118000000.0,-631000000.0,-615000000.0,NaN
Financing Cash Flow,-40781000000.0,-19500000000.0,-22136000000.0,-50728000000.0,NaN
Cash Flow From Continuing Financing Activities,-40781000000.0,-19500000000.0,-22136000000.0,-50728000000.0,NaN
Net Other Financing Charges,-14047000000.0,-7123000000.0,-3251000000.0,-5514000000.0,NaN
Cash Dividends Paid,-5072000000.0,0.0,0.0,NaN,NaN
Common Stock Dividend Paid,-5072000000.0,0.0,0.0,NaN,NaN
Net Common Stock Issuance,-30125000000.0,-19774000000.0,-27956000000.0,-44537000000.0,NaN
Common Stock Payments,-30125000000.0,-19774000000.0,-27956000000.0,-44537000000.0,NaN
Net Issuance Payments Of Debt,8463000000.0,7397000000.0,9071000000.0,-677000000.0,NaN
Net Short Term Debt Issuance,NaN,NaN,NaN,14000000.0,24000000.0
Net Long Term Debt Issuance,8463000000.0,7397000000.0,9071000000.0,-677000000.0,NaN
Long Term Debt Payments,-1969000000.0,-1058000000.0,-850000000.0,-677000000.0,NaN
Long Term Debt Issuance,10432000000.0,8455000000.0,9921000000.0,0.0,NaN
Investing Cash Flow,-47150000000.0,-24495000000.0,-28970000000.0,-7570000000.0,NaN
Cash Flow From Continuing Investing Activities,-47150000000.0,-24495000000.0,-28970000000.0,-7570000000.0,NaN
Net Other Investing Changes,129000000.0,-23000000.0,-4000000.0,-331000000.0,NaN
Net Investment Purchase And Sale,-9753000000.0,3202000000.0,3532000000.0,12179000000.0,NaN
Sale Of Investment,15789000000.0,6184000000.0,13158000000.0,42586000000.0,NaN
Purchase Of Investment,-25542000000.0,-2982000000.0,-9626000000.0,-30407000000.0,NaN
Net Business Purchase And Sale,-270000000.0,-629000000.0,-1312000000.0,-851000000.0,NaN
Purchase Of Business,-270000000.0,-629000000.0,-1312000000.0,-851000000.0,NaN
Net PPE Purchase And Sale,-37256000000.0,-27045000000.0,-31186000000.0,-18567000000.0,NaN
Sale Of PPE,NaN,221000000.0,245000000.0,123000000.0,48000000.0
Purchase Of PPE,-37256000000.0,-27045000000.0,-31186000000.0,-18690000000.0,NaN
Operating Cash Flow,91328000000.0,71113000000.0,50475000000.0,57683000000.0,NaN
Cash Flow From Continuing Operating Activities,91328000000.0,71113000000.0,50475000000.0,57683000000.0,NaN
Change In Working Capital,1048000000.0,3836000000.0,5683000000.0,700000000.0,NaN
Change In Other Working Capital,NaN,NaN,NaN,187000000.0,108000000.0
Change In Other Current Liabilities,2805000000.0,624000000.0,886000000.0,941000000.0,NaN
Change In Other Current Assets,-270000000.0,-80000000.0,-106000000.0,-349000000.0,NaN
Change In Payables And Accrued Expense,696000000.0,5132000000.0,4510000000.0,4968000000.0,NaN
Change In Accrued Expense,323000000.0,5081000000.0,4300000000.0,3544000000.0,NaN
Change In Payable,373000000.0,51000000.0,210000000.0,1424000000.0,NaN
Change In Account Payable,373000000.0,51000000.0,210000000.0,1436000000.0,NaN
Change In Prepaid Assets,-698000000.0,559000000.0,162000000.0,-1750000000.0,NaN
Change In Receivables,-1485000000.0,-2399000000.0,231000000.0,-3110000000.0,NaN
Changes In Account Receivables,-1485000000.0,-2399000000.0,231000000.0,-3110000000.0,NaN
Other Non Cash Items,87000000.0,411000000.0,1982000000.0,-127000000.0,NaN
Stock Based Compensation,16690000000.0,14027000000.0,11992000000.0,9164000000.0,NaN
Unrealized Gain Loss On Investment Securities,NaN,NaN,463000000.0,-232000000.0,33000000.0
Asset Impairment Charge,383000000.0,2432000000.0,2218000000.0,0.0,NaN
Deferred Tax,-4738000000.0,131000000.0,-3286000000.0,609000000.0,NaN
Deferred Income Tax,-4738000000.0,131000000.0,-3286000000.0,609000000.0,NaN
Depreciation Amortization Depletion,15498000000.0,11178000000.0,8686000000.0,7967000000.0,NaN
Depreciation And Amortization,15498000000.0,11178000000.0,8686000000.0,7967000000.0,NaN
Net Income From Continuing Operations,62360000000.0,39098000000.0,23200000000.0,39370000000.0,NaN

In [17]:
ticker.quarterly_cashflow

,2024-12-31,2024-09-30,2024-06-30,2024-03-31,2023-12-31,2023-09-30,2023-06-30
Free Cash Flow,13563000000.0,16466000000.0,11197000000.0,12846000000.0,11739000000.0,NaN,NaN
Repurchase Of Capital Stock,0.0,-8818000000.0,-6299000000.0,-15008000000.0,-5942000000.0,NaN,NaN
Repayment Of Debt,-411000000.0,-944000000.0,-299000000.0,-315000000.0,-307000000.0,NaN,NaN
Issuance Of Debt,0.0,10432000000.0,NaN,NaN,0.0,0.0,NaN
Capital Expenditure,-14425000000.0,-8258000000.0,-8173000000.0,-6400000000.0,-7665000000.0,NaN,NaN
Interest Paid Supplemental Data,130000000.0,111000000.0,124000000.0,121000000.0,146000000.0,NaN,NaN
Income Tax Paid Supplemental Data,2228000000.0,1767000000.0,5929000000.0,630000000.0,4591000000.0,NaN,NaN
End Cash Position,45438000000.0,45127000000.0,33026000000.0,33284000000.0,42827000000.0,NaN,NaN
Beginning Cash Position,45127000000.0,33026000000.0,33284000000.0,42827000000.0,37900000000.0,NaN,NaN
Effect Of Exchange Rate Changes,-714000000.0,368000000.0,-152000000.0,-288000000.0,396000000.0,NaN,NaN
Changes In Cash,1025000000.0,11733000000.0,-106000000.0,-9255000000.0,4531000000.0,NaN,NaN
Financing Cash Flow,-5465000000.0,-4371000000.0,-11178000000.0,-19767000000.0,-8401000000.0,NaN,NaN
Cash Flow From Continuing Financing Activities,-5465000000.0,-4371000000.0,-11178000000.0,-19767000000.0,-8401000000.0,NaN,NaN
Net Other Financing Charges,-3784000000.0,-3778000000.0,-3314000000.0,-3171000000.0,-2152000000.0,NaN,NaN
Cash Dividends Paid,-1270000000.0,-1263000000.0,-1266000000.0,-1273000000.0,NaN,0.0,NaN
Common Stock Dividend Paid,-1270000000.0,-1263000000.0,-1266000000.0,-1273000000.0,NaN,0.0,NaN
Net Common Stock Issuance,0.0,-8818000000.0,-6299000000.0,-15008000000.0,-5942000000.0,NaN,NaN
Common Stock Payments,0.0,-8818000000.0,-6299000000.0,-15008000000.0,-5942000000.0,NaN,NaN
Net Issuance Payments Of Debt,-411000000.0,9488000000.0,-299000000.0,-315000000.0,-307000000.0,NaN,NaN
Net Long Term Debt Issuance,-411000000.0,9488000000.0,-299000000.0,-315000000.0,-307000000.0,NaN,NaN
Long Term Debt Payments,-411000000.0,-944000000.0,-299000000.0,-315000000.0,-307000000.0,NaN,NaN
Long Term Debt Issuance,0.0,10432000000.0,NaN,NaN,0.0,0.0,NaN
Investing Cash Flow,-21498000000.0,-8620000000.0,-8298000000.0,-8734000000.0,-6472000000.0,NaN,NaN
Cash Flow From Continuing Investing Activities,-21498000000.0,-8620000000.0,-8298000000.0,-8734000000.0,-6472000000.0,NaN,NaN
Net Other Investing Changes,17000000.0,124000000.0,NaN,NaN,-3000000.0,-10000000.0,-85000000.0
Net Investment Purchase And Sale,-7081000000.0,-354000000.0,-56000000.0,-2262000000.0,1187000000.0,NaN,NaN
Sale Of Investment,3817000000.0,4114000000.0,3233000000.0,4625000000.0,2359000000.0,NaN,NaN
Purchase Of Investment,-10898000000.0,-4468000000.0,-3289000000.0,-6887000000.0,-1172000000.0,NaN,NaN
Net Business Purchase And Sale,-9000000.0,-132000000.0,-57000000.0,-72000000.0,-64000000.0,NaN,NaN
Purchase Of Business,-9000000.0,-132000000.0,-57000000.0,-72000000.0,-64000000.0,NaN,NaN
Net PPE Purchase And Sale,-14425000000.0,-8258000000.0,-8173000000.0,-6400000000.0,-7592000000.0,NaN,NaN
Sale Of PPE,NaN,NaN,NaN,NaN,73000000.0,47000000.0,82000000.0
Purchase Of PPE,-14425000000.0,-8258000000.0,-8173000000.0,-6400000000.0,-7665000000.0,NaN,NaN
Operating Cash Flow,27988000000.0,24724000000.0,19370000000.0,19246000000.0,19404000000.0,NaN,NaN
Cash Flow From Continuing Operating Activities,27988000000.0,24724000000.0,19370000000.0,19246000000.0,19404000000.0,NaN,NaN
Change In Working Capital,-504000000.0,2070000000.0,-741000000.0,223000000.0,-1271000000.0,NaN,NaN
Change In Other Current Liabilities,1114000000.0,901000000.0,707000000.0,83000000.0,663000000.0,NaN,NaN
Change In Other Current Assets,-200000000.0,-29000000.0,53000000.0,-94000000.0,-111000000.0,NaN,NaN
Change In Payables And Accrued Expense,2090000000.0,1239000000.0,-247000000.0,-2386000000.0,320000000.0,NaN,NaN
Change In Accrued Expense,1522000000.0,572000000.0,-497000000.0,-1274000000.0,-350000000.0,NaN,NaN
Change In Payable,568000000.0,667000000.0,250000000.0,-1112000000.0,670000000.0,NaN,NaN
Change In Account Payable,568000000.0,667000000.0,250000000.0,-1112000000.0,594000000.0,NaN,NaN
Change In Prepaid Assets,-530000000.0,-184000000.0,-84000000.0,100000000.0,700000000.0,NaN,NaN
Change In Receivables,-2978000000.0,143000000.0,-1170000000.0,2520000000.0,-2843000000.0,NaN,NaN
Changes In Account Receivables,-2978000000.0,143000000.0,-1170000000.0,2520000000.0,-2843000000.0,NaN,NaN
Other Non Cash Items,169000000.0,-11000000.0,-5000000.0,-66000000.0,133000000.0,NaN,NaN
Stock Based Compensation,4262000000.0,4250000000.0,4616000000.0,3562000000.0,3424000000.0,NaN,NaN
Asset Impairment Charge,95000000.0,8000000.0,40000000.0,240000000.0,1090000000.0,NaN,NaN
Deferred Tax,-1332000000.0,-1308000000.0,-1642000000.0,-456000000.0,-1161000000.0,NaN,NaN
Deferred Income Tax,-1332000000.0,-1308000000.0,-1642000000.0,-456000000.0,-1161000000.0,NaN,NaN
Depreciation Amortization Depletion,4460000000.0,4027000000.0,3637000000.0,3374000000.0,3172000000.0,NaN,NaN
Depreciation And Amortization,4460000000.0,4027000000.0,3637000000.0,3374000000.0,3172000000.0,NaN,NaN
Net Income From Continuing Operations,20838000000.0,15688000000.0,13465000000.0,12369000000.0,14017000000.0,NaN,NaN

In [21]:
ticker.income_stmt

,2024-12-31,2023-12-31,2022-12-31,2021-12-31,2020-12-31
Tax Effect Of Unusual Items,-81420000.0,-64416000.0,-15795000.0,-23380000.0,NaN
Tax Rate For Calcs,0.118,0.176,0.195,0.167,NaN
Normalized EBITDA,87566000000.0,59418000000.0,37771000000.0,55414000000.0,NaN
Total Unusual Items,-690000000.0,-366000000.0,-81000000.0,-140000000.0,NaN
Total Unusual Items Excluding Goodwill,-690000000.0,-366000000.0,-81000000.0,-140000000.0,NaN
Net Income From Continuing Operation Net Minority Interest,62360000000.0,39098000000.0,23200000000.0,39370000000.0,NaN
Reconciled Depreciation,15498000000.0,11178000000.0,8686000000.0,7967000000.0,NaN
Reconciled Cost Of Revenue,30161000000.0,25959000000.0,25249000000.0,22649000000.0,NaN
EBITDA,86876000000.0,59052000000.0,37690000000.0,55274000000.0,NaN
EBIT,71378000000.0,47874000000.0,29004000000.0,47307000000.0,NaN
Net Interest Income,1973000000.0,1043000000.0,-44000000.0,671000000.0,NaN
Interest Expense,715000000.0,446000000.0,185000000.0,23000000.0,NaN
Interest Income,2517000000.0,1639000000.0,461000000.0,484000000.0,NaN
Normalized Income,62968580000.0,39399584000.0,23265205000.0,39486620000.0,NaN
Net Income From Continuing And Discontinued Operation,62360000000.0,39098000000.0,23200000000.0,39370000000.0,NaN
Total Expenses,95121000000.0,88151000000.0,87665000000.0,71176000000.0,NaN
Total Operating Income As Reported,69380000000.0,46751000000.0,28944000000.0,46753000000.0,NaN
Diluted Average Shares,2614000000.0,2629000000.0,2702000000.0,2859000000.0,NaN
Basic Average Shares,2534000000.0,2574000000.0,2687000000.0,2815000000.0,NaN
Diluted EPS,23.86,14.87,8.59,13.77,NaN
Basic EPS,24.61,15.19,8.63,13.99,NaN
Diluted NI Availto Com Stockholders,62360000000.0,39098000000.0,23200000000.0,39370000000.0,NaN
Net Income Common Stockholders,62360000000.0,39098000000.0,23200000000.0,39370000000.0,NaN
Otherunder Preferred Stock Dividend,NaN,NaN,NaN,NaN,0.0
Net Income,62360000000.0,39098000000.0,23200000000.0,39370000000.0,NaN
Net Income Including Noncontrolling Interests,62360000000.0,39098000000.0,23200000000.0,39370000000.0,NaN
Net Income Continuous Operations,62360000000.0,39098000000.0,23200000000.0,39370000000.0,NaN
Tax Provision,8303000000.0,8330000000.0,5619000000.0,7914000000.0,NaN
Pretax Income,70663000000.0,47428000000.0,28819000000.0,47284000000.0,NaN
Other Income Expense,-690000000.0,-366000000.0,-81000000.0,-140000000.0,NaN
Other Non Operating Income Expenses,NaN,NaN,-320000000.0,210000000.0,-34000000.0
Special Income Charges,NaN,NaN,NaN,0.0,0.0
Gain On Sale Of Security,-690000000.0,-366000000.0,-81000000.0,-140000000.0,NaN
Net Non Operating Interest Income Expense,1973000000.0,1043000000.0,-44000000.0,671000000.0,NaN
Total Other Finance Cost,-171000000.0,150000000.0,320000000.0,-210000000.0,NaN
Interest Expense Non Operating,715000000.0,446000000.0,185000000.0,23000000.0,NaN
Interest Income Non Operating,2517000000.0,1639000000.0,461000000.0,484000000.0,NaN
Operating Income,69380000000.0,46751000000.0,28944000000.0,46753000000.0,NaN
Operating Expense,64960000000.0,62192000000.0,62416000000.0,48527000000.0,NaN
Research And Development,43873000000.0,38483000000.0,35338000000.0,24655000000.0,NaN
Selling General And Administration,21087000000.0,23709000000.0,27078000000.0,23872000000.0,NaN
Selling And Marketing Expense,11347000000.0,12301000000.0,15262000000.0,14043000000.0,NaN
General And Administrative Expense,9740000000.0,11408000000.0,11816000000.0,9829000000.0,NaN
Other Gand A,9740000000.0,11408000000.0,11816000000.0,9829000000.0,NaN
Gross Profit,134340000000.0,108943000000.0,91360000000.0,95280000000.0,NaN
Cost Of Revenue,30161000000.0,25959000000.0,25249000000.0,22649000000.0,NaN
Total Revenue,164501000000.0,134902000000.0,116609000000.0,117929000000.0,NaN
Operating Revenue,162779000000.0,133844000000.0,115801000000.0,117208000000.0,NaN

In [19]:
ticker.quarterly_earnings

### Sustainability: Environmental, Social and Governance (ESG)

In [22]:
ticker.sustainability

                                                                           esgScores
maxAge                                                                         86400
totalEsg                                                                       32.73
environmentScore                                                                2.41
socialScore                                                                    21.64
governanceScore                                                                 8.68
ratingYear                                                                      2025
ratingMonth                                                                        3
highestControversy                                                               4.0
peerCount                                                                        597
esgPerformance                                                             LEAD_PERF
peerGroup                                                        Software & Services
relatedControversy                                              [Customer Incidents]
peerEsgScorePerformance            {'min': 7.44, 'avg': 20.78758793969849, 'max':...
peerGovernancePerformance          {'min': 1.34, 'avg': 5.662929687499999, 'max':...
peerSocialPerformance              {'min': 4.49, 'avg': 9.885351562499995, 'max':...
peerEnvironmentPerformance         {'min': 0.05, 'avg': 3.057656249999999, 'max':...
peerHighestControversyPerformance  {'min': 0.0, 'avg': 0.6566164154103853, 'max':...
percentile                                                                      None
environmentPercentile                                                           None
socialPercentile                                                                None
governancePercentile                                                            None
adult                                                                          False
alcoholic                                                                      False
animalTesting                                                                  False
catholic                                                                        None
controversialWeapons                                                           False
smallArms                                                                      False
furLeather                                                                     False
gambling                                                                       False
gmo                                                                            False
militaryContract                                                               False
nuclear                                                                        False
pesticides                                                                     False
palmOil                                                                        False
coal                                                                           False
tobacco                                                                        False

### Analyst Recommendations

In [23]:
ticker.recommendations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   period      4 non-null      object
 1   strongBuy   4 non-null      int64
 2   buy         4 non-null      int64
 3   hold        4 non-null      int64
 4   sell        4 non-null      int64
 5   strongSell  4 non-null      int64
dtypes: int64(5), object(1)
memory usage: 324.0+ bytes

In [24]:
ticker.recommendations.tail(10)

  period  strongBuy  buy  hold  sell  strongSell
0     0m         13   42     6     0           2
1    -1m         12   44     7     0           2
2    -2m         12   43     7     0           2
3    -3m         12   46     8     0           2

### Upcoming Events

In [25]:
ticker.calendar

{'Dividend Date': datetime.date(2025, 3, 25),
 'Ex-Dividend Date': datetime.date(2025, 3, 13),
 'Earnings Date': [datetime.date(2025, 4, 22), datetime.date(2025, 4, 28)],
 'Earnings High': 5.9,
 'Earnings Low': 4.7,
 'Earnings Average': 5.23788,
 'Revenue High': 42724000000,
 'Revenue Low': 40377000000,
 'Revenue Average': 41456276240}

### Option Expiration Dates

In [26]:
ticker.options

('2025-03-21',
 '2025-03-28',
 '2025-04-04',
 '2025-04-11',
 '2025-04-17',
 '2025-04-25',
 '2025-05-16',
 '2025-06-20',
 '2025-07-18',
 '2025-08-15',
 '2025-09-19',
 '2025-10-17',
 '2025-12-19',
 '2026-01-16',
 '2026-03-20',
 '2026-06-18',
 '2026-12-18',
 '2027-01-15',
 '2027-12-17')

In [27]:
expiration = ticker.options[0]

In [28]:
options = ticker.option_chain(expiration)

In [29]:
options.calls.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 191 entries, 0 to 190
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   contractSymbol     191 non-null    object
 1   lastTradeDate      191 non-null    datetime64[ns, UTC]
 2   strike             191 non-null    float64
 3   lastPrice          191 non-null    float64
 4   bid                191 non-null    float64
 5   ask                191 non-null    float64
 6   change             191 non-null    float64
 7   percentChange      191 non-null    float64
 8   volume             186 non-null    float64
 9   openInterest       191 non-null    int64
 10  impliedVolatility  191 non-null    float64
 11  inTheMoney         191 non-null    bool
 12  contractSize       191 non-null    object
 13  currency           191 non-null    object
dtypes: bool(1), datetime64[ns, UTC](1), float64(8), int64(1), object(3)
memory usage: 19.7+ KB

In [30]:
options.calls.head()

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,META250321C00005000,2025-03-13 19:15:28+00:00,5.0,594.93,601.55,603.60,5.429993,0.921118,2.0,1,20.460941,True,REGULAR,USD
1,META250321C00010000,2025-03-13 19:15:28+00:00,10.0,584.55,596.55,598.85,0.000000,0.000000,370.0,0,11.875003,True,REGULAR,USD
2,META250321C00015000,2025-03-13 19:15:28+00:00,15.0,579.60,591.45,593.85,0.000000,0.000000,25.0,0,9.875004,True,REGULAR,USD
3,META250321C00020000,2025-03-13 19:15:28+00:00,20.0,574.55,586.55,588.95,0.000000,0.000000,145.0,0,10.062504,True,REGULAR,USD
4,META250321C00025000,2025-03-03 17:20:13+00:00,25.0,644.90,581.05,583.95,0.000000,0.000000,2.0,0,12.519533,True,REGULAR,USD

In [31]:
options.puts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170 entries, 0 to 169
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   contractSymbol     170 non-null    object
 1   lastTradeDate      170 non-null    datetime64[ns, UTC]
 2   strike             170 non-null    float64
 3   lastPrice          170 non-null    float64
 4   bid                170 non-null    float64
 5   ask                170 non-null    float64
 6   change             170 non-null    float64
 7   percentChange      170 non-null    float64
 8   volume             156 non-null    float64
 9   openInterest       170 non-null    int64
 10  impliedVolatility  170 non-null    float64
 11  inTheMoney         170 non-null    bool
 12  contractSize       170 non-null    object
 13  currency           170 non-null    object
dtypes: bool(1), datetime64[ns, UTC](1), float64(8), int64(1), object(3)
memory usage: 17.6+ KB

## Data Download with proxy server

You can use a proxy server to avoid having your IP blacklisted as illustrated below (but need an actual PROXY_SERVER).

In [27]:
PROXY_SERVER = 'PROXY_SERVER'

The following will only work with proper PROXY_SERVER...

In [28]:
# msft = yf.Ticker("MSFT")

# msft.history(proxy=PROXY_SERVER)
# msft.get_actions(proxy=PROXY_SERVER)
# msft.get_dividends(proxy=PROXY_SERVER)
# msft.get_splits(proxy=PROXY_SERVER)
# msft.get_balance_sheet(proxy=PROXY_SERVER)
# msft.get_cashflow(proxy=PROXY_SERVER)
# msft.option_chain(proxy=PROXY_SERVER)

## Downloading multiple symbols

In [32]:
tickers = yf.Tickers('msft aapl goog')

In [33]:
tickers

yfinance.Tickers object <MSFT,AAPL,GOOG>

In [34]:
pd.Series(tickers.tickers['MSFT'].info)

address1                         One Microsoft Way
city                                       Redmond
state                                           WA
zip                                     98052-6399
country                              United States
                                       ...
fiftyTwoWeekRange                  376.91 - 468.35
fiftyTwoWeekHighChange                   -79.79001
fiftyTwoWeekHighChangePercent            -0.170364
displayName                              Microsoft
trailingPegRatio                            1.7766
Length: 180, dtype: object

In [35]:
tickers.tickers['AAPL'].history(period="1mo")

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-02-18 00:00:00-05:00,244.149994,245.179993,241.839996,244.470001,48822500,0.0,0.0
2025-02-19 00:00:00-05:00,244.660004,246.009995,243.160004,244.869995,32204200,0.0,0.0
2025-02-20 00:00:00-05:00,244.940002,246.779999,244.289993,245.830002,32316900,0.0,0.0
2025-02-21 00:00:00-05:00,245.949997,248.690002,245.220001,245.550003,53197400,0.0,0.0
2025-02-24 00:00:00-05:00,244.929993,248.860001,244.419998,247.100006,51326400,0.0,0.0
2025-02-25 00:00:00-05:00,248.000000,250.000000,244.910004,247.039993,48013300,0.0,0.0
2025-02-26 00:00:00-05:00,244.330002,244.979996,239.130005,240.360001,44433600,0.0,0.0
2025-02-27 00:00:00-05:00,239.410004,242.460007,237.059998,237.300003,41153600,0.0,0.0
2025-02-28 00:00:00-05:00,236.949997,242.089996,230.199997,241.839996,56833400,0.0,0.0
2025-03-03 00:00:00-05:00,241.789993,244.029999,236.110001,238.029999,47184000,0.0,0.0
2025-03-04 00:00:00-05:00,237.710007,240.070007,234.679993,235.929993,53798100,0.0,0.0
2025-03-05 00:00:00-05:00,235.419998,236.550003,229.229996,235.740005,47227600,0.0,0.0
2025-03-06 00:00:00-05:00,234.440002,237.860001,233.160004,235.330002,45170400,0.0,0.0
2025-03-07 00:00:00-05:00,235.110001,241.369995,234.759995,239.070007,46273600,0.0,0.0
2025-03-10 00:00:00-04:00,235.539993,236.160004,224.220001,227.479996,72071200,0.0,0.0
2025-03-11 00:00:00-04:00,223.809998,225.839996,217.449997,220.839996,76137400,0.0,0.0
2025-03-12 00:00:00-04:00,220.139999,221.750000,214.910004,216.979996,62547500,0.0,0.0
2025-03-13 00:00:00-04:00,215.949997,216.839996,208.419998,209.679993,61368300,0.0,0.0
2025-03-14 00:00:00-04:00,211.250000,213.949997,209.580002,213.490005,60060200,0.0,0.0

In [36]:
tickers.history(period='1mo').stack(-1)

[*********************100%***********************]  3 of 3 completed

Price                   Close  Dividends        High         Low        Open  \
Date       Ticker
2025-02-18 AAPL    244.470001       0.00  245.179993  241.839996  244.149994
           GOOG    185.588562       0.00  187.566304  183.371087  187.226695
           MSFT    408.820282       0.00  409.778352  405.686551  407.183549
2025-02-19 AAPL    244.869995       0.00  246.009995  243.160004  244.660004
           GOOG    186.917053       0.00  187.146787  185.288903  185.973121
           MSFT    413.940002       0.00  414.658563  406.834255  407.063806
2025-02-20 AAPL    245.830002       0.00  246.779999  244.289993  244.940002
           GOOG    186.427612       0.00  186.907062  184.389940  186.287772
           MSFT    416.130005       0.83  419.309998  412.540009  415.290009
2025-02-21 AAPL    245.550003       0.00  248.690002  245.220001  245.949997
           GOOG    181.373367       0.00  187.256664  180.923882  187.076861
           MSFT    408.209991       0.00  418.049988  407.890015  417.339996
2025-02-24 AAPL    247.100006       0.00  248.860001  244.419998  244.929993
           GOOG    180.983810       0.00  184.879366  180.674166  183.590841
           MSFT    404.000000       0.00  409.369995  399.320007  408.510010
2025-02-25 AAPL    247.039993       0.00  250.000000  244.910004  248.000000
           GOOG    177.168152       0.00  180.554293  176.568844  179.949986
           MSFT    397.899994       0.00  401.920013  396.700012  401.100006
2025-02-26 AAPL    240.360001       0.00  244.979996  239.130005  244.330002
           GOOG    174.501190       0.00  177.877349  173.392453  176.743646
           MSFT    399.730011       0.00  403.600006  394.250000  398.010010
2025-02-27 AAPL    237.300003       0.00  242.460007  237.059998  239.410004
           GOOG    170.016312       0.00  176.389041  169.558825  175.739787
           MSFT    392.529999       0.00  405.739990  392.170013  401.269989
2025-02-28 AAPL    241.839996       0.00  242.089996  230.199997  236.949997
           GOOG    172.024017       0.00  172.303697  168.198374  170.106204
           MSFT    396.989990       0.00  397.630005  386.570007  392.660004
2025-03-03 AAPL    238.029999       0.00  244.029999  236.110001  241.789993
           GOOG    168.468079       0.00  174.800860  167.449235  173.532301
           MSFT    388.489990       0.00  398.820007  386.160004  398.820007
2025-03-04 AAPL    235.929993       0.00  240.070007  234.679993  237.710007
           GOOG    172.413574       0.00  174.965659  167.349336  167.748890
           MSFT    388.609985       0.00  392.579987  381.000000  383.399994
2025-03-05 AAPL    235.740005       0.00  236.550003  229.229996  235.419998
           GOOG    174.790878       0.00  175.550008  170.735486  172.123918
           MSFT    401.019989       0.00  401.670013  388.809998  389.339996
2025-03-06 AAPL    235.330002       0.00  237.860001  233.160004  234.440002
           GOOG    174.011765       0.00  176.528886  172.311690  172.353650
           MSFT    396.890015       0.00  402.149994  392.679993  394.279999
2025-03-07 AAPL    239.070007       0.00  241.369995  234.759995  235.110001
           GOOG    175.550003       0.00  176.698688  172.053986  173.044861
           MSFT    393.309998       0.00  394.799988  385.540009  392.320007
2025-03-10 AAPL    227.479996       0.00  236.160004  224.220001  235.539993
           GOOG    167.809998       0.20  170.449997  165.565002  170.160004
           MSFT    380.160004       0.00  386.399994  377.220001  385.839996
2025-03-11 AAPL    220.839996       0.00  225.839996  217.449997  223.809998
           GOOG    165.979996       0.00  168.654999  163.240005  166.679993
           MSFT    380.450012       0.00  386.000000  376.910004  379.000000
2025-03-12 AAPL    216.979996       0.00  221.750000  214.910004  220.139999
           GOOG    169.000000       0.00  169.529999  165.479996  168.470001
           MSFT    383.269989       0.00  385.220001  378.950012  382.950012
2025-03-13 AAPL    209.679993       0.00  216.839996  208.419998  215.949997
           GOOG    164.729996       0.00  168.119995  164.070007  167.979996
           MSFT    378.769989       0.00  385.320007  377.450012  383.160004
2025-03-14 AAPL    213.490005       0.00  213.949997  209.580002  211.250000
           GOOG    167.619995       0.00  168.250000  164.509995  165.315002
           MSFT    388.559998       0.00  390.230011  379.510010  379.779999

Price              Stock Splits    Volume
Date       Ticker
2025-02-18 AAPL             0.0  48822500
           GOOG             0.0  19796000
           MSFT             0.0  21423100
2025-02-19 AAPL             0.0  32204200
           GOOG             0.0  13120500
           MSFT             0.0  24114200
2025-02-20 AAPL             0.0  32316900
           GOOG             0.0  12063800
           MSFT             0.0  23508700
2025-02-21 AAPL             0.0  53197400
           GOOG             0.0  19520800
           MSFT             0.0  27524800
2025-02-24 AAPL             0.0  51326400
           GOOG             0.0  18734000
           MSFT             0.0  26443700
2025-02-25 AAPL             0.0  48013300
           GOOG             0.0  20832500
           MSFT             0.0  29387400
2025-02-26 AAPL             0.0  44433600
           GOOG             0.0  23637200
           MSFT             0.0  19619000
2025-02-27 AAPL             0.0  41153600
           GOOG             0.0  25930500
           MSFT             0.0  21127400
2025-02-28 AAPL             0.0  56833400
           GOOG             0.0  30049800
           MSFT             0.0  32845700
2025-03-03 AAPL             0.0  47184000
           GOOG             0.0  24122000
           MSFT             0.0  23007700
2025-03-04 AAPL             0.0  53798100
           GOOG             0.0  30711400
           MSFT             0.0  29342900
2025-03-05 AAPL             0.0  47227600
           GOOG             0.0  18848000
           MSFT             0.0  23433100
2025-03-06 AAPL             0.0  45170400
           GOOG             0.0  19082400
           MSFT             0.0  23304600
2025-03-07 AAPL             0.0  46273600
           GOOG             0.0  16395300
           MSFT             0.0  22034100
2025-03-10 AAPL             0.0  72071200
           GOOG             0.0  28990700
           MSFT             0.0  32840100
2025-03-11 AAPL             0.0  76137400
           GOOG             0.0  23705900
           MSFT             0.0  30380200
2025-03-12 AAPL             0.0  62547500
           GOOG             0.0  19880100
           MSFT             0.0  24253600
2025-03-13 AAPL             0.0  61368300
           GOOG             0.0  15206200
           MSFT             0.0  20473000
2025-03-14 AAPL             0.0  60060200
           GOOG             0.0  18592900
           MSFT             0.0  19929300

In [37]:
data = yf.download("SPY AAPL", start="2020-01-01", end="2020-01-05")

[                       0%                       ]

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  2 of 2 completed

In [38]:
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2 entries, 2020-01-02 to 2020-01-03
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   (Close, AAPL)   2 non-null      float64
 1   (Close, SPY)    2 non-null      float64
 2   (High, AAPL)    2 non-null      float64
 3   (High, SPY)     2 non-null      float64
 4   (Low, AAPL)     2 non-null      float64
 5   (Low, SPY)      2 non-null      float64
 6   (Open, AAPL)    2 non-null      float64
 7   (Open, SPY)     2 non-null      float64
 8   (Volume, AAPL)  2 non-null      int64
 9   (Volume, SPY)   2 non-null      int64
dtypes: float64(8), int64(2)
memory usage: 176.0 bytes

In [39]:
data = yf.download(
        tickers = "SPY AAPL MSFT", # list or string

        # use "period" instead of start/end
        # valid periods: 1d,5d,1mo,3mo,6mo,1y,2y,5y,10y,ytd,max
        # (optional, default is '1mo')
        period = "5d",

        # fetch data by interval (including intraday if period < 60 days)
        # valid intervals: 1m,2m,5m,15m,30m,60m,90m,1h,1d,5d,1wk,1mo,3mo
        # (optional, default is '1d')
        interval = "1m",

        # group by ticker (to access via data['SPY'])
        # (optional, default is 'column')
        group_by = 'ticker',

        # adjust all OHLC automatically
        # (optional, default is False)
        auto_adjust = True,

        # download pre/post regular market hours data
        # (optional, default is False)
        prepost = True,

        # use threads for mass downloading? (True/False/Integer)
        # (optional, default is True)
        threads = True,

        # proxy URL scheme use use when downloading?
        # (optional, default is None)
        proxy = None
    )

[*********************100%***********************]  3 of 3 completed

In [40]:
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 4741 entries, 2025-03-10 09:00:00+00:00 to 2025-03-14 23:59:59+00:00
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   (AAPL, Open)    4590 non-null   float64
 1   (AAPL, High)    4590 non-null   float64
 2   (AAPL, Low)     4590 non-null   float64
 3   (AAPL, Close)   4590 non-null   float64
 4   (AAPL, Volume)  4590 non-null   float64
 5   (SPY, Open)     4664 non-null   float64
 6   (SPY, High)     4664 non-null   float64
 7   (SPY, Low)      4664 non-null   float64
 8   (SPY, Close)    4664 non-null   float64
 9   (SPY, Volume)   4664 non-null   float64
 10  (MSFT, Open)    4441 non-null   float64
 11  (MSFT, High)    4441 non-null   float64
 12  (MSFT, Low)     4441 non-null   float64
 13  (MSFT, Close)   4441 non-null   float64
 14  (MSFT, Volume)  4441 non-null   float64
dtypes: float64(15)
memory usage: 592.6 KB

In [48]:
import yfinance as yf
# download dataframe
data = yf.download('SPY',
                          start='2017-01-01',
                          end='2019-04-30',
                          auto_adjust=True)

[*********************100%***********************]  1 of 1 completed

In [49]:
# auto_adjust = True
data.tail()

Price            Close        High         Low        Open    Volume
Ticker             SPY         SPY         SPY         SPY       SPY
Date
2019-04-23  267.663849  267.901473  265.415656  265.653252  52246600
2019-04-24  267.069794  267.919717  266.923566  267.581577  50392900
2019-04-25  266.905304  267.572463  265.698973  266.969284  57770900
2019-04-26  268.148102  268.221202  266.164921  266.950892  50916400
2019-04-29  268.568481  269.098560  268.148094  268.239490  57197700

In [47]:
# auto_adjust = False
data.tail()

Price,Adj Close,Close,High,Low,Open,Volume
Ticker,SPY,SPY,SPY,SPY,SPY,SPY
Date,,,,,,
2019-04-23,267.663849,292.880005,293.140015,290.420013,290.679993,52246600
2019-04-24,267.069794,292.230011,293.160004,292.070007,292.790009,50392900
2019-04-25,266.905304,292.049988,292.779999,290.730011,292.119995,57770900
2019-04-26,268.148102,293.410004,293.489990,291.239990,292.100006,50916400
2019-04-29,268.568481,293.869995,294.450012,293.410004,293.510010,57197700